### ISSUE TITLE
Allow payments from more countries

### ISSUE THREAD

**Issue by yegortimoshenko** [liberapay/liberapay.com#1008]
Hi, I like the idea of your service, but I can't use it because my card is issued in Russia and apparently MangoPay blocks such cards. If this requires changing the payment gateway, please consider that option.

**Comment by yegortimoshenko** [comment]
Currently Mangopay blocks 70 countries out of [~195 countries in the world](http://www.worldometers.info/geography/how-many-countries-are-there-in-the-world/):

https://mangopay.desk.com/customer/en/portal/articles/2299163-which-are-the-black-listed-countries-where-you-can-t-process-pay-ins-

**Comment by Changaco** [comment]
Unfortunately there isn't much we can do about this.

Russia is blacklisted because of the sanctions that were adopted in response to the Ukraine crisis. Other countries are blacklisted for a variety of reasons including concerns around money laundering and terrorism financing.

Related issues: #729 and #374.

**Comment by yegortimoshenko** [comment]
> Russia is blacklisted because of the sanctions that were adopted in response to the Ukraine crisis. 

Notably, Ukraine is blacklisted as well.

> Other countries are blacklisted for a variety of reasons including concerns around money laundering and terrorism financing.

That does not explain why wire transfers are still accepted. If anything, current blacklist only stops people from donating to creators: people who finance wars/terrorism would have a much easier time justifying $15 wire transfer fee (the minimum in Russia).

> Unfortunately there isn't much we can do about this.

This restriction is very easy to circumvent via an intermediate offshore bank by anyone who really has malicious intent.

This is an inherently unjust and bureaucratic thing to do, people should not be associated with their respective governments. Borders are not natural.

I should note that this is the very first time I've encountered this. Clearly, there are plenty payment gateways that have less restrictive blacklists.

At the very least, make it clear for people with IP addresses from blocked countries, at registration, that they can't actually use your service to donate.

Please find a different payment gateway.

**Comment by Changaco** [comment]
Mangopay's not a payment gateway, and right now they're still the best partner for us despite their shortcomings, because their competitors aren't really better.

I already told Mangopay that their policy makes no sense if it only applies to one payment method. I also asked them if they could make an exception and unblock Russia for Liberapay, they said no.

**Comment by yegortimoshenko** [comment]
In light of #1171 (https://medium.com/liberapay-blog/liberapay-is-in-trouble-b58b40714d82), I hope you choose a payment processor that's more accepting of people living in countries like Russia.

**Comment by Changaco** [comment]
We've switched from Mangopay to Stripe and PayPal, hopefully that solves the problem.

**Comment by yegortimoshenko** [comment]
It does, thank you! :-)

**Comment by lachs0r** [comment]
Unfortunately, neither Stripe nor PayPal will allow people in Ukraine to receive payments.
