### ISSUE TITLE
Display error: Giving amount changes even without clicking on "change"?

### ISSUE THREAD

**Issue by rugk** [liberapay/liberapay.com#1026]
Still at giving page.

STR:
1. Change amount of currency at giving page for one line. (Do _not_ click on the "Change" button.)
2. Press F5 to reload site.

What happens: The changed amount is displayed.

What should happen: The previous, correct, amount is displayed.

Maybes that is some curios caching bug, as it does not happen when I reload with Ctrl+F5.

Firefox 59

**Comment by Changaco** [comment]
That's normal browser behavior, F5 preserves modified input values.

**Comment by rugk** [comment]
Hu? Any reference for that? IMHO this is not the normal behaviour, F5 always reloads the site – with all form data.

**Comment by rugk** [comment]
E.g. when I try it [here](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_text), it is just as usual: the form data is lost.
Also this old [Stackexchange questions](https://stackoverflow.com/questions/9423165/keep-form-data-on-page-refresh) asks to do what exactly you here seem to do accidentally – preserve the form data on refresh.

**Comment by Changaco** [comment]
> Hu? Any reference for that? IMHO this is not the normal behaviour, F5 always reloads the site – with all form data.

https://developer.mozilla.org/en-US/docs/Web/API/Location/reload has some information on the differences between the two kinds of page reloads, but it doesn't mention form persistence.

If you dig into the HTML specifications linked in that page you'll find [this paragraph](https://www.w3.org/TR/html50/browsers.html#an-entry-with-persisted-user-state) which does mention forms: “For example, some user agents might want to persist the scroll position, or the values of form controls.”

> E.g. when I try it [here](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_text), it is just as usual: the form data is lost.

Because that page creates the form dynamically with JavaScript.

**Comment by rugk** [comment]
Ah ok, did not know about this. Thanks FYI.
