### ISSUE TITLE
Nationalities of donors

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1102]
Some organizations cannot accept donations from foreign nationals, thus they are currently unable to use Liberapay.

**Comment by Mikaela** [comment]
It seems that in Finland the opposite may be true, https://github.com/liberapay/liberapay.org/issues/30#issuecomment-508131168, Finns can receive donations from foreigners, but receiving donations from people located in Finland requires a money collecting permit from authorities and that won't be given for individuals.

I guess Liberapay should have option to either whitelist or blacklist countires, so if someone cannot receive donations from foreigners, they could whitelist their own country, and Finns could blacklist Finland.

**Comment by revi** [comment]
This would also resolve #1280 as well.

**Comment by Changaco** [comment]
Implementation guide:

- create a `donor_nationalities` column in the `participants` table
- create `www/%username/edit/nationalities.spt` based on `www/%username/edit/currencies.spt`
- modify `templates/macros/nav.html`: add the new Nationalities page to the settings nav
- modify `templates/macros/your-tip.html`: ask the donor to select their nationality if the recipient doesn't accept all of them
- modify `www/%username/tip.spt`: check the donor's nationality if the recipient doesn't accept all of them

**Comment by Mikaela** [comment]
I have recently took the risk of starting to use LiberaPay also for receiving regardless of #30 and would very much appreciate this feature to reduce the risk of law violation and I think I am far from alone in that.

Currently my only protection is telling readers of my Finnish (and through machine translation Swedish) profile rudely to go away due to the law and I don't know whether that is enough to be considered to not be appealing to Finnish residing public with the language the UI I cannot control uses.

Speaking of which I think in the case of #30, permanent or long term residence is more relevant than nationality which the issue title refers to. Other considerations would be multiple nationalities/residencies and bank account or payment card countries in case LiberaPay is aware of those.

**Comment by Changaco** [comment]
I've pushed an initial implementation in #2302. It looks at two sources of information to determine the country of origin: the donor's IP address and the donor's payment instrument. The first one is merely a guess and only results in a warning being displayed in the donation form. The second one isn't a guess and results in a payment being rejected.

> Additionally I think there is demand in blocking supporters from conflict areas, especially Russia in the west.

Blocking donations from Russia would have very little impact as it's almost impossible to donate from Russia anyway due to the restrictions put in place by the big card networks (Visa and Mastercard). It also seems counterproductive to me, as donations coming from Russia deplete Russia's foreign currency reserves and fuel Russia's internal inflation.

**Comment by Changaco** [comment]
The initial implementation is finally complete and will be deployed later this week.

**Comment by Changaco** [comment]
Done: https://liberapay.com/about/me/edit/countries
