### ISSUE TITLE
Empty wallet error number 400

### ISSUE THREAD

**Issue by Strit** [liberapay/liberapay.com#1172]
When I go to the Empty Wallet page and click the "Donate the rest of wallet to people I donate too" button and press proceed, I just get an error 400 page, saying it did not go through.

Any reason for this?

**Comment by his10** [comment]
#1169 @Changaco

**Comment by Changaco** [comment]
A 400 error is most likely a problem on the receiving side, as mentioned in the blog post "for example someone who hasn’t filled the identity form or a team that hasn’t defined how the income should be split between the members".

Please post a link to your account so that I can look into the issue.

**Comment by Strit** [comment]
That makes sense.

Here's my [account](https://liberapay.com/Strit/).

**Comment by Changaco** [comment]
@Strit The team you're trying to donate to doesn't have any nonzero takes, so our software doesn't know how to split the money.

**Comment by Strit** [comment]
I'm part of that team, but it does not work if I take the cut either.

How can I distribute it amongst the others?

**Comment by downeym** [comment]
Same problem [for me](https://liberapay.com/downey), too.
