### ISSUE TITLE
Still mention of Mangopay in notifications

### ISSUE THREAD

**Issue by SGallay** [liberapay/liberapay.com#1213]
The weekly notifications still mention Mangopay as the name of the account.

<img width="468" alt="screen shot 2018-08-17 at 15 47 59" src="https://user-images.githubusercontent.com/5243958/44269626-69fdb080-a235-11e8-871f-8dc9e3e6e202.png">

**Comment by mattbk** [comment]
Mangopay is still working, so transactions are still occurring. We are continuing to transition, however.

**Comment by mattbk** [comment]
Yeah, it doesn't make much sense. So you probably still have money trickling into your Mangopay wallet from other people's wallets every payday. 

Stripe will only work if a person giving to you has donated (via credit card) since you added your stripe account. They will get a screen like this:

![image](https://user-images.githubusercontent.com/3729038/44273819-23449200-a206-11e8-987a-5cf1c080151d.png)

@SGallay, I've attempted to send you $1.00 but am getting an error message:

![image](https://user-images.githubusercontent.com/3729038/44276254-93eead00-a20c-11e8-8f88-189e74fcab12.png)

@Changaco, I'm not sure if this is a Liberapay error ID code or a Stripe one.

@SGallay, do you see any failed payments on your Stripe dashboard?

**Comment by SGallay** [comment]
No failed payment on my side.

I see three CHF 0.98 payments dated today.

--

**Comment by mattbk** [comment]
Ha! Looks like you get my $3 for helping debug!

So that's what it looks like when you receive money through Stripe.

**Comment by Changaco** [comment]
> @Changaco, I'm not sure if this is a Liberapay error ID code or a Stripe one.

It's not a Stripe error, your screenshot shows a standard Liberapay error page containing a Sentry error ID.
