### ISSUE TITLE
Stripe and privacy concerns

### ISSUE THREAD

**Issue by MathiasRenner** [liberapay/liberapay.com#1268]
@Changaco and the Liberapay Team: Thank you for your great work for Liberapay. I love Liberapay very much, and want continue using and supporting it. But there's one thing I don't understand: Stripe. I don't have a good feeling about Stripe due to privacy concerns. 

Some Notes on that:
- I found others being also concerned here: https://social.tchncs.de/@kuketzblog/100547288512637237 (unfortunately, only in german)
- It's a US company, which meanwhile has to stick to the EU-GDPR - but reading the privacy policy I don't get a good feeling (https://stripe.com/de/privacy#how-we-disclose-personal-data)
- Liberapy is FLOSS and supports FLOSS. People like FLOSS because - amongst other reasons - you can self-host it and have data control. So far all of this is a perfect fit. But to me, this beautiful story gets a sad ending with Stripe.

I am sure your decision for Strips is the result of many discussions, and you probably did a deep research about payment methods and provider (for SEPA). So maybe there is just no other solution, which would be very sad to me.

All in all I wanna give you guys just the feedback that me and maybe other FLOSS lovers (which is probably the most interesting of your target groups) might have problems using Liberapay with Stripe.

**Comment by trebmuh** [comment]
>  an additional privacy-aware payment option would be awesome

@MathiasRenner : we've been actively searching for a replacement of the previous operator (mangopay) but didn't find one fitting with our needs yet. If someone knows one, please share the knowledge here.

**Comment by Changaco** [comment]
I agree that Stripe's privacy policy isn't perfect, the section "c. Interest-based advertising." in particular is problematic, however I do not think that Stripe should be avoided. As a payment service provider their primary business model is to charge fees for each transaction they process, so they don't need ads. With public pressure and the GDPR it should be possible to make them abandon any bad thing that they might be doing with user data. I recommend to any EU citizen who has concerns about using Stripe to send questions to Stripe's Data Protection Officer, whose email address is dpo@stripe.com (according to [Stripe's "Privacy Center" page](https://stripe.com/privacy-center/legal)), and if the answer isn't satisfactory, to report Stripe to your [national Data Protection Authority](https://en.wikipedia.org/wiki/National_data_protection_authority).

**Comment by axre** [comment]
I always thought one argument for using floss is you are in control of your data. Started using Liberapay because of 3 reasons - it's floss, few fees, makes my support easier to manage.

Now there's no argument for using Liberapay.

- it has the same (high) fees as any other donation option
- it has the same privacy concerns
- it's not easier than donating directly (clicking the donate button from PayPal for example)

If people are not using liberapay anymore its not a surprise.

**Comment by trebmuh** [comment]
@axre we are still looking for a good payment operator and have looked and analyze a bunch of what's available right now. No luck so far. If you know of a good one, please, let us now.

**Comment by IzzySoft** [comment]
@trebmuh @Changaco I don't see what @axre wrote is criticizing *you* – it's simply stating the facts. Most F(L)OSS people avoid Paypal (I wouldn't dare using it myself on either end, donor or receiver); and for those who think different, simply pushing a Paypal button would 1) be less complicated and 2) avoid the "man in the middle" (again, no offense meant). And Stripe isn't an option for most of us either ("Pest or Cholera?").

It's really unfortunate no real alternative seems to exist. Again: no one said you didn't try, or didn't try hard enough – we just state the "status quo" and look what information is available – and what might possibly be done (or even already in the works).

My account is dead since Mango kicked you out. It lived just for about 2 months, and went better for me than Flattr did in years. So it hurts losing you – but currently we ("tin foils" if you want) are dead in the tracks with our accounts. Some are already planning their leave. I just had integrated the LP buttons in my site(s) … but currently don't see how I can use it.

Thanks again for all your affords. And please count our "speaking out" here not as "blaming you" – but rather as "not yet given up hope on LP". :crossed_fingers:

**Comment by Changaco** [comment]
It was a good idea to open this issue but I think it's time to close it now. There is no evidence that Stripe is doing anything bad with the data they have, and if there was any evidence then the proper course of action would be to make them stop by using the GDPR. Boycotting Stripe doesn't solve anything, it's only shooting yourselves in the foot.

I've opened a new issue for the possible support of a third payment processor as an alternative to Stripe and PayPal: #1394.

@axre

- In some cases the fees are higher now than they were with Mangopay, but it's only a temporary setback.
- Mangopay required collecting *more* personal information from donors than Stripe. Also, just because Mangopay is based in the EU doesn't guarantee that they respect the GDPR any better than more global processors like Stripe and PayPal.
- Using Liberapay is easier than donating directly, both for the donor who can manage multiple donations from the same account and for the recipient who doesn't have to handle any aspect of the payment processing.

**Comment by Changaco** [comment]
Some of the comments on https://framasphere.org/posts/8670207 are about this issue.
