### ISSUE TITLE
Invitation notification doesn't dismiss

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#133]
Since I received my first team invitation, I have a pending notification that stay even if I already accept the invitation. Click again on it display the invitation notification, and clicking on accept again display the following badly encoded message:

    Vous avez dÃ©jÃ  acceptÃ© cette invitation.

**Comment by Changaco** [comment]
You have to click the little `×` button on the notifications page. I know, this UI sucks. The underlying problem is that notifications don't have a status, so we can't mark them as read, only delete them. We need to:

- [ ] add a status column to the `notification_queue` table
- [ ] automatically mark notifications as read when the user opens them

**Comment by Phyks** [comment]
Hi,

I just noticed this same issue today (still having the possibility to "accept" or "reject" an invitation from the notifications, although I already did it). As far as I understood, this should have been closed and fixed by #262, isn't it?

Thanks!

**Comment by Changaco** [comment]
@Phyks Please see #535 for the current situation.
