### ISSUE TITLE
Failure to connect Organization repository

### ISSUE THREAD

**Issue by Sigmanor** [liberapay/liberapay.com#1524]
When I try to connect my organization to my Liberapay account, from [this ](https://liberapay.com/on/github/Crypto-Notepad)page:

![image](https://user-images.githubusercontent.com/7986067/60081801-3041e400-973b-11e9-8648-10cb8662a43d.png)

I get this error:
![image](https://user-images.githubusercontent.com/7986067/60081968-92024e00-973b-11e9-9364-4a228d2e1611.png)

When I checking permissions, I see that:

![image](https://user-images.githubusercontent.com/7986067/60081160-ee646e00-9739-11e9-8ab4-28779ac7cbe5.png)

How I can add organization repository to my account?

**Comment by mattbk** [comment]
I think this is because the GitHub org has no public members. The Liberapay permission is only for public information. 

![image](https://user-images.githubusercontent.com/3729038/60106331-a558ed80-972a-11e9-9da1-1d9da4feab02.png)

If possible, you could temporarily make yourself a public member of the org while you connect. I'm not sure if there is any checking after that.

**Comment by Sigmanor** [comment]
@mattbk Yes, making  me a public member helps. Thank you!
