### ISSUE TITLE
Router component for tracking fees

### ISSUE THREAD

**Issue by abitrolly** [liberapay/liberapay.com#1732]
Today starts a 3 days https://theglobalhack.com/ hackathon which could be a good way to solve itches that are waiting for too long to be scratched.

The one particular itch is that in my country we have several ways to transfer money between people and organizations. Even for the same VISA way, the fees can be different. I want fee transparency, and in theory it should be possible to calculate fees by tracking transactions.

I thought that Liberapay could be a great platform to add fee tracking component, which is basically the difference between sent money and amount "received - fee". The main question is to understand what APIs are available to track the money in target account, and how to preserve the anonymity. Maybe the "Money Router" should be an external script that gets data both from Liberapay and from bank account, finds transaction and compares them together. Creating a list of "shady" bank/institutions that specifically make this operation hard would also be a good outcome of these 3 days.

The deadline for submission is 6 hours and I registered https://devpost.com/software/money-router to reserve the spot. It requires a team of 4 people.

@Changaco does that make sense for Liberapay?

**Comment by Changaco** [comment]
I think that your problem has very little to do with Liberapay, that it has nothing to do with “The Global Hack” which is described as “Fighting a Global Crisis - 3 billion people in lockdown. Let's hack the future so we never go through this again.”, and that obsessing over banking fees is a waste of time.

I also think that your idea of building an observatory of banking fees by analyzing transactions on both ends wouldn't work, because you wouldn't be able to get enough data to produce meaningful results.

The solution to avoid obscure and unexpected transaction fees is to avoid international bank transfers coordinated through [SWIFT](https://www.swift.com/), by using alternatives like [TransferWise](https://transferwise.com/), Stripe and PayPal.

**Comment by abitrolly** [comment]
@Changaco now that you've mentioned that I realize that TransferWise, Stripe and PayPal and not do not require having a banking account, but they still might have connection to the global financial network to prevent "money printing".
