### ISSUE TITLE
Limiting currencies doesn't affect existing donations

### ISSUE THREAD

**Issue by LiamDawe** [liberapay/liberapay.com#1931]
Hi, I have our Liberapay account tagged only for GBP but it seems to do nothing. We've still had people donate with USD, CHF, NOK and so on.

Looks like a bug with allowing multi currencies through still?

**Comment by Changaco** [comment]
The change you made to the list of currencies you accept did have an effect. If you look at https://liberapay.com/gamingonlinux/donate you can see that there isn't a currency selector, and that the first Frequently Asked Question displayed is:

> #### Can I donate in another currency?
>
> No, gamingonlinux only accepts payments in British Pound.

However, changing the accepted currencies doesn't affect existing donations, that's why you're still seeing incoming payments in foreign currencies. You should have seen a warning message about that when you changed your settings (“You currently receive the equivalent of £XX.XX per week from donations in foreign currencies. These donations will not be converted to your main currency.”).

I'm planning to modify what the currency settings do, so I would be interested in knowing why you decided to accept only one currency and whether the new system described in #1862 would be problematic for you.

**Comment by LiamDawe** [comment]
Stripe is a special case, because the money doesn't touch us until it's in our native currency. The problem I have is PayPal, because multi-currency and exchange rates and so on, it becomes a nuisance to log it all for taxes which is why I prefer to limit it to my own currency.

**Comment by Changaco** [comment]
Okay, so the new system would be better for you since it would prevent donors from sending foreign currencies through PayPal.

I'm curious, do you use PayPal's automatic currency conversion? That's what I do to simplify my accounting. The foreign currency amounts are visible in my PayPal ledger, but I ignore them and use the converted amounts instead.

**Comment by LiamDawe** [comment]
The only way I am aware to have it auto convert is to not have the currency setup, and in PayPal's settings tell it to auto convert. That's not foolproof though. Even if I only have £ setup in PayPal, it will at random for _bigger_ sums open a $ balance instead of auto converting. PayPal is a huge nuisance.

**Comment by Changaco** [comment]
> Even if I only have £ setup in PayPal, it will at random for _bigger_ sums open a $ balance instead of auto converting.

I've never heard of that before. Did it happen to you multiple times?

**Comment by LiamDawe** [comment]
Yes, happens all the time and I am trying to get them to look into why but that's out of scope of this ticket ;)

**Comment by LiamDawe** [comment]
Hi, is there any update on this? I really only want to have payments made via GBP on my Liberapay.

**Comment by Changaco** [comment]
I haven't worked on #1862 yet, sorry.

Have you considered disconnecting your PayPal account from Liberapay? Most of the donations you receive through Liberapay are processed by Stripe, and you already accept PayPal donations outside of Liberapay, so the loss from not having PayPal as a payment method in Liberapay should be minimal.

**Comment by LiamDawe** [comment]
It's not just PayPal, Stripe too. The whole point, again, of picking a specific currency is to only get that.

**Comment by Changaco** [comment]
Based on your previous comments, I thought your problem was only with PayPal, since Stripe properly converts the funds into your currency.

Regarding the issue that restricting the accepted currencies doesn't do anything to existing donations, I guess we should require each donor to accept the currency change at the time of their next renewal.

**Comment by LiamDawe** [comment]
> I guess we should require each donor to accept the currency change at the time of their next renewal.

That would be the proper way to sort this.

**Comment by Changaco** [comment]
(I started working on this last month.)
