### ISSUE TITLE
Why is one time donation not available?

### ISSUE THREAD

**Issue by benbullard79** [liberapay/liberapay.com#1979]
I had a regular scheduled donation. I wanted to make an additional one time donation. I was unable to find an option for this and had to delete my regularly scheduled donation to make the one time donation.

Is that necessary? Would it not make more sense to keep the regular scheduled donation and allow for folks to also make a one time donation? Or did I just miss something?

It seems like you would want to make it as easy as possible for folks to be able to do both. Have a regularly scheduled donation and in addition make additional one time donations. This sort of seems like it should be in Non-profit fundraising 101.

**Comment by Changaco** [comment]
One-time donations aren't supported yet because the initial concept of Liberapay was to provide an income as stable as possible by focusing on recurrent donations. See #415 and #1584 for more details.

**Comment by ashledombos** [comment]
If I'm correct, @benbullard79 is less bothered by the fact that one cannot pay with a one-time donation than by the fact that a recurring donation has to be deleted in order to exceptionally increase the value of the donation. In other words, by the fact of not being able to vary the amount of the recurring donation on the fly.

**Comment by Changaco** [comment]
@ashledombos I think you misunderstood. It's always been possible to modify the amount of a recurrent donation at any time.
