### ISSUE TITLE
stripe country availability is outdated

### ISSUE THREAD

**Issue by the-j0k3r** [liberapay/liberapay.com#2076]
See https://liberapay.com/about/payment-processors

>PayPal is available to creators in more than [200 countries](https://www.paypal.com/webapps/mpp/country-worldwide), whereas Stripe only supports [39 countries](https://stripe.com/global).

When visiting the link under 39 countries you find that's really now 46 https://stripe.com/global

![image](https://user-images.githubusercontent.com/31389848/136521666-291e9d17-4fe6-4c66-af61-c05ecd2d1f0f.png)

**Comment by Changaco** [comment]
The numbers never match, because we don't count the “Preview” or request-only countries as supported.

Brazil isn't in our list because so far all payment attempts have failed with the error message “Stripe doesn't currently support destination charges with accounts in BR.”

United Arab Emirates isn't in our list because it hasn't been tested yet.
