### ISSUE TITLE
Bounties

### ISSUE THREAD

**Issue by theoryshaw** [liberapay/liberapay.com#2140]
**User Story:**
Start a bounty and have others add to the funding as well.

For example, I created the following bounty on Bountysource, I seeded it with $100. I then used my social network to campaign for others to contribute to it. As you can see, we are up to $2860.

In short, I'd like to do the same with Liberapay

https://app.bountysource.com/issues/95048565-make-construction-drawing-generation-like-really-really-awesome

**Comment by Changaco** [comment]
> In short, I'd like to do the same with Liberapay

Why? What would be the added value in using Liberapay for bounties instead of Bountysource?

The main reason why Liberapay doesn't do bounties is that [bounties don't really work](https://wiki.snowdrift.coop/market-research/history/software#bounties). Recurrent donations are much more effective at funding the proper maintenance and development of a project.

Another reason why Liberapay doesn't support feature-specific payments is that they're not donations, so there would be legal and tax issues to work out.

**Comment by theoryshaw** [comment]
Sounds good. Will close.

**Comment by Cwpute** [comment]
> What would be the added value in using Liberapay for bounties instead of Bountysource?

In 2020, Bountysource was acquired by a cryptocurrency company that immediately tried to retroactively change its TOS. It didn't work out in the end, but people in the FOSS community who were using Bountysource before were more than worried something bad would happen down the line. Namely, [Nextcloud decided not to promote the use of Bountysource anymore](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).
since then a good bunch of other websites have popped up trying to offer a public place for opensource bounties, but none survived. Liberapay, could fill that purpose.

Now, i've read the market research for Snowdrift, but there is an argument to be had for smaller repos and/or organizations. Putting bounties on quiet projects can help raise awareness on useful software that needs maintaining. Bounties on busy projects with only a few maintainers can help relieve some hard work from them.
On the other other hand, bounties in general do not follow the ethics of opensource software, incentivizing people to hide their PR until it's done, at the risk of it being badly thought of, badly implemented, documented, organized etc.

All in all i'm very split up. But if it can help some, mabe it's good enough to consider it ?

**Comment by wiki-me** [comment]
> since then a good bunch of other websites have popped up trying to offer a public place for opensource bounties, but none survived. Liberapay, could fill that purpose.

There is [rysolv](https://rysolv.com/) , although it could use some work , there is sometime a security error when using certain urls , see [this](https://github.com/rysolv/rysolv/issues/248).
