### ISSUE TITLE
OpenStreetMap authorization fails

### ISSUE THREAD

**Issue by almereyda** [liberapay/liberapay.com#222]
When I try to connect my OSM account, their interface tells my I had decided to deny the connection request, despite I didn't.

**Comment by Changaco** [comment]
I am able to reproduce the issue. It looks like the problem is on their end, but we might be able to work around it.

**Comment by Changaco** [comment]
This is fixed. The problem was as I thought: our apps weren't requesting any permissions, not even read access to the user's preferences. Their software doesn't support that, it sees that no permissions were granted by the user and mistakenly concludes that the user denied access. If you have the time please report this issue upstream to OSM.
