### ISSUE TITLE
You need at least €2.00 to cover your donations next week. Why is this showing up?

### ISSUE THREAD

**Issue by hugoroger** [liberapay/liberapay.com#540]
Hi everyone!

I`m getting the notifications below but I dont understand how they are being generated. What team do I owe money to and how? All I ever did was accept an invite to join a team.

"Greetings,
You have €0.00 left in your Liberapay wallet, but you need at least €2.00 to cover your donations next week."

**Comment by Changaco** [comment]
According to our records 2 weeks ago you set up two 1€/week donations. You can see that on [your Giving page](https://liberapay.com/about/me/giving). Since you only receive 0.50 euros per week your income does not cover your donations, so our software rightly concludes that you need to add money to your account in order to give 2 euros per week.
