### ISSUE TITLE
Past month stats on the front page are misleading.

### ISSUE THREAD

**Issue by aggsol** [liberapay/liberapay.com#730]
They state to be of the past month which is September but the for example the new user count increases even September is over. But it is also not the current month as the number did not reset on October 1st. I guess it's within the past 30 days?! Then the wording is wrong or at least misleading.

**Comment by Changaco** [comment]
Yes, "past month" means "past 30 days" in this case. We also use "this week" instead of "in the last 7 days" in some cases.

Why "month" instead of "30 days"? Because we don't want to use a number here, it would distract the reader from the numbers that matter (i.e. the number of new accounts, etc).

**Comment by aggsol** [comment]
Ok, I see. Still it feels wrong especially at the beginning of a month. You could always spell "thirty" ;-P I'll close the issue.
