### ISSUE TITLE
Accepting foreign currencies complicates matter – no detailed explanation

### ISSUE THREAD

**Issue by rugk** [liberapay/liberapay.com#873]
> Fremdwährungen zu akzeptieren verkompliziert die Sache für Sie. Sie abzulehen, kann aber Unterstützer davon abhalten zu spenden.

So what? There is no explanation of why this complicates all that… I mean the money goes to Liberapay first anyway, so you can "exchange" the currencies, can't you?
So at least a help/doc link or so is missing there, which provides a detailed explanation including tradeoffs, pros, cons and so on…

**Comment by jorgesumle** [comment]
Es ist einfacher für Personen nur eine Währung zu akzeptieren. Mit Fremdwährungen ist es komplizierter weil man die Umwaldung, Ziel... rechnen muss. 

> I mean the money goes to Liberapay first anyway, so you can "exchange" the currencies, can't you?

Nein, wir können noch nicht Währungen umrechnen. Hoffentlich werden wir es schaffen: https://github.com/liberapay/liberapay.com/issues/835

---

It is simpler for people to accept only a currency. With foreign currencies it's more difficult because you have to calculate rates, goals...

> I mean the money goes to Liberapay first anyway, so you can "exchange" the currencies, can't you?

No, we can't swap coins yet. I hope that we can implement it: https://github.com/liberapay/liberapay.com/issues/835

**Comment by rugk** [comment]
Ah okay so it basically is just complicate, because of https://github.com/liberapay/liberapay.com/issues/835. So maybe state ", because we cannot convert them for you", or directly link to the issue?

**Comment by Changaco** [comment]
There's also the matter of withdrawal fees. If the person is in SEPA and only accepts euros then they'll never pay any withdrawal fee, but if they also accept US dollars then they'll have to pay $3.51 per withdrawal in this currency.
