### ISSUE TITLE
Search only searches in description in current language

### ISSUE THREAD

**Issue by MCMic** [liberapay/liberapay.com#880]
Hello,

When searching for «Godot», I do not find Akien profile even if it mentions this word.
It only works if I first set the website to english.

This is a big problem as it makes searching for people working on any software kind of hard. (I’d have to try each language manually?)

**Comment by akien-mga** [comment]
I haven't checked the way it's implemented, but I'd expect the search to use this priority:
- Search for statements in current language (e.g. French)
- If there is no statement for a user in the current language(*), search for statements in English

(*) Or maybe even if there is but if there is no match? To also take into account users who might have e.g. a very brief statement in French and a long one in English, including the targeted word.

**Comment by trebmuh** [comment]
> When searching for «Godot», I do not find Akien profile even if it mentions this word.
> It only works if I first set the website to english.

Confirmed.

**Comment by trebmuh** [comment]
@MCMic @akien-mga I've retested right now, and akien's profile is found wether [searching in the website set in French](https://fr.liberapay.com/search?q=godot) or [in English](https://fr.liberapay.com/search?q=godot).

Can you please confirm that this issue is can be close?
_( @MCMic as the one who open the issue, you can close it yourself, so do it so please )_

**Comment by MCMic** [comment]
Confirmed to work
